/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as RagRouteImport } from './routes/rag'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as InterviewRouteImport } from './routes/interview'
import { Route as GapRouteImport } from './routes/gap'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as AnalysisJdRouteImport } from './routes/analysis-jd'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as IndexRouteImport } from './routes/index'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const RagRoute = RagRouteImport.update({
  id: '/rag',
  path: '/rag',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewRoute = InterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const GapRoute = GapRouteImport.update({
  id: '/gap',
  path: '/gap',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisJdRoute = AnalysisJdRouteImport.update({
  id: '/analysis-jd',
  path: '/analysis-jd',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/analysis-jd': typeof AnalysisJdRoute
  '/assessment': typeof AssessmentRoute
  '/gap': typeof GapRoute
  '/interview': typeof InterviewRoute
  '/jobs': typeof JobsRoute
  '/offers': typeof OffersRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/rag': typeof RagRoute
  '/resume': typeof ResumeRoute
  '/roadmap': typeof RoadmapRoute
  '/tasks': typeof TasksRoute
  '/upload': typeof UploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/analysis-jd': typeof AnalysisJdRoute
  '/assessment': typeof AssessmentRoute
  '/gap': typeof GapRoute
  '/interview': typeof InterviewRoute
  '/jobs': typeof JobsRoute
  '/offers': typeof OffersRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/rag': typeof RagRoute
  '/resume': typeof ResumeRoute
  '/roadmap': typeof RoadmapRoute
  '/tasks': typeof TasksRoute
  '/upload': typeof UploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/analysis-jd': typeof AnalysisJdRoute
  '/assessment': typeof AssessmentRoute
  '/gap': typeof GapRoute
  '/interview': typeof InterviewRoute
  '/jobs': typeof JobsRoute
  '/offers': typeof OffersRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/rag': typeof RagRoute
  '/resume': typeof ResumeRoute
  '/roadmap': typeof RoadmapRoute
  '/tasks': typeof TasksRoute
  '/upload': typeof UploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/analysis-jd'
    | '/assessment'
    | '/gap'
    | '/interview'
    | '/jobs'
    | '/offers'
    | '/profile'
    | '/projects'
    | '/rag'
    | '/resume'
    | '/roadmap'
    | '/tasks'
    | '/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis'
    | '/analysis-jd'
    | '/assessment'
    | '/gap'
    | '/interview'
    | '/jobs'
    | '/offers'
    | '/profile'
    | '/projects'
    | '/rag'
    | '/resume'
    | '/roadmap'
    | '/tasks'
    | '/upload'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/analysis-jd'
    | '/assessment'
    | '/gap'
    | '/interview'
    | '/jobs'
    | '/offers'
    | '/profile'
    | '/projects'
    | '/rag'
    | '/resume'
    | '/roadmap'
    | '/tasks'
    | '/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRoute: typeof AnalysisRoute
  AnalysisJdRoute: typeof AnalysisJdRoute
  AssessmentRoute: typeof AssessmentRoute
  GapRoute: typeof GapRoute
  InterviewRoute: typeof InterviewRoute
  JobsRoute: typeof JobsRoute
  OffersRoute: typeof OffersRoute
  ProfileRoute: typeof ProfileRoute
  ProjectsRoute: typeof ProjectsRoute
  RagRoute: typeof RagRoute
  ResumeRoute: typeof ResumeRoute
  RoadmapRoute: typeof RoadmapRoute
  TasksRoute: typeof TasksRoute
  UploadRoute: typeof UploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rag': {
      id: '/rag'
      path: '/rag'
      fullPath: '/rag'
      preLoaderRoute: typeof RagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview': {
      id: '/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof InterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gap': {
      id: '/gap'
      path: '/gap'
      fullPath: '/gap'
      preLoaderRoute: typeof GapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis-jd': {
      id: '/analysis-jd'
      path: '/analysis-jd'
      fullPath: '/analysis-jd'
      preLoaderRoute: typeof AnalysisJdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRoute: AnalysisRoute,
  AnalysisJdRoute: AnalysisJdRoute,
  AssessmentRoute: AssessmentRoute,
  GapRoute: GapRoute,
  InterviewRoute: InterviewRoute,
  JobsRoute: JobsRoute,
  OffersRoute: OffersRoute,
  ProfileRoute: ProfileRoute,
  ProjectsRoute: ProjectsRoute,
  RagRoute: RagRoute,
  ResumeRoute: ResumeRoute,
  RoadmapRoute: RoadmapRoute,
  TasksRoute: TasksRoute,
  UploadRoute: UploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
